services:
  - type: web
    name: powerup-sa-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ESKOM_API_KEY
        sync: false
      - key: PORT
        value: 10000